name: Flutter Linux Build

on:
    push:
        tags:
        - '*'

jobs:
    build_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
            - run: |
                  sudo apt-get update -y
                  sudo apt-get install -y ninja-build libgtk-3-dev
            - run: flutter pub get
            - run: flutter config --enable-linux-desktop
            - run: flutter pub run realm generate
            - run: flutter gen-l10n
            - run: flutter build linux --release
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: aspis-${{github.ref_name}}-linux.zip
                directory: build/linux/x64/release/bundle
            - name: Linux Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: build/linux/x64/release/bundle/aspis-${{github.ref_name}}-linux.zip
