# name: Flutter iOS Build

# on:
#     push:
#         tags:
#         - '*'

# jobs:
#     build_ios:
#         runs-on: macos-latest
#         steps:
#             - uses: actions/checkout@v3
#             - uses: subosito/flutter-action@v2
#               with:
#                   channel: "stable"
#                   architecture: x64
#             - run: flutter pub get
#             - run: flutter pub run realm generate
#             - run: flutter gen-l10n
#             - run: flutter build ipa --release --no-codesign
#             - name: Release
#               uses: softprops/action-gh-release@v1
#               if: startsWith(github.ref, 'refs/tags/')
#               env:
#                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#               with:
#                 files: |
#                     /Users/runner/work/aspis/aspis/build/ios/archive/*.xcarchive
#                     /Users/runner/work/aspis/aspis/build/ios/ipa/*.ipa
